theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
k = { j = "normal_mode" } # Maps `kj` to exit insert mode
